# The namespace of the collection Everything as Code Team
namespace: "esp"

# The name of the collection. Has the same character restrictions as 'namespace'
name: "terraform"

# The version of the collection. Must be compatible with semantic versioning
version: 0.1.0

# The path to the Markdown (.md) readme file. This path is relative to the root of the collection
readme: README.md

# A list of the collection's content authors.
authors:
- Krzysztof Lewandowski (@klewan)

# A short summary description of the "esp.terraform" collection
description: Ansible collection that interacts with the Terraform Cloud/Enterprise API.

license_file: COPYING

# A list of tags you want to associate with the collection for indexing/searching. A tag name has the same character
# requirements as 'namespace' and 'name'
tags:
  - hashicorp
  - terraform
  - automation

# Collections that this collection requires to be installed for it to be usable. The key of the dict is the
# collection label 'namespace.name'.
dependencies: {}

# The URL of the originating SCM repository
repository: https://github.com/NordeaOSS/esp.terraform.git

# The URL to any online docs
documentation: https://github.com/NordeaOSS/esp.terraform.git/blob/master/README.md
